# Default values for my-argocd-helm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: "my-angular-FE"

image:
  repository: salekin/nginx-halo
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

